import Head from 'next/head'
import Header from '../components/header'
import Footer from '../components/footer'
import Navbar from '../components/navbar'
import ScreenView from '../Screens/View/screenView'

import { useState } from 'react';
import { Poppins } from "next/font/google";

const poppins = Poppins(
  { 
    weight: ['400', '700'],
    subsets: ['latin'], 
  }
)
export default function Home() {
  const [screenActive, setScreenActive] = useState("Dashboard");
  const [tableActive, setTableActive] = useState("");
  const [kotActive, setkotActive] = useState("");
  return (
    <>
      <Head>
        <title>Point-of-sale</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <style jsx global>
          {
            `
              html {
                font-family: ${poppins.style.fontFamily};
              }
              .btn{
                font-family: ${poppins.style.fontFamily};
              }
            `
          }
        </style>
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@48,400,0,0" />
      </Head>
      <main class="main">
        <div>
          <Header state = {screenActive}></Header>
          <div class="body">
            <Navbar screenActive = {[screenActive, setScreenActive]} tableActive = {[tableActive,setTableActive]} kotActive = {[kotActive,setkotActive]}></Navbar>
            <ScreenView screenActive = {screenActive} tableActive = {[tableActive,setTableActive]} kotActive = {[kotActive,setkotActive]}>
            </ScreenView>
          </div>
        </div>
        <Footer params={tableActive}></Footer>
      </main>
    </>
  )
}




