import Head from 'next/head'
import Header from '../components/header'
import Footer from '../components/footer'
import Navbar from '../components/navbar'
import ScreenView from '../Screens/View/screenView'
import { Inter } from 'next/font/google'
const inter = Inter({ subsets: ['latin'] })
import { useState } from 'react';

export default function Home() {
  const [screenActive, setScreenActive] = useState('POS');
  const [tableActive, setTableActive] = useState("");
  const [kotActive, setkotActive] = useState('');
  return (
    <>
      <Head>
        <title>Point-of-sale</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@48,400,0,0" />
      </Head>
      <main class="main">
        <div>
          <Header state = {screenActive}></Header>
          <div class="body">
            <Navbar screenActive = {[screenActive, setScreenActive]} tableActive = {[tableActive,setTableActive]} kotActive = {[kotActive,setkotActive]}></Navbar>
            <ScreenView screenActive = {screenActive} tableActive = {[tableActive,setTableActive]} kotActive = {[kotActive,setkotActive]}>
            </ScreenView>
          </div>
        </div>
        <Footer state={tableActive}></Footer>
      </main>
    </>
  )
}




